<?php
include_once 'includes/auth.php';
include_once 'config/database.php';

$risk_id = isset($_GET['id']) ? (int)$_GET['id'] : 0;

if (!$risk_id) {
    header("Location: risk_owner_dashboard.php");
    exit();
}

$database = new Database();
$db = $database->getConnection();

// Get risk details
$query = "SELECT r.*, u1.full_name as reporter_name, u2.full_name as owner_name
          FROM risk_incidents r
          LEFT JOIN users u1 ON r.reported_by = u1.id
          LEFT JOIN users u2 ON r.risk_owner_id = u2.id
          WHERE r.id = :risk_id";

$stmt = $db->prepare($query);
$stmt->bindParam(':risk_id', $risk_id);
$stmt->execute();
$risk = $stmt->fetch(PDO::FETCH_ASSOC);

if (!$risk) {
    header("Location: risk_owner_dashboard.php");
    exit();
}

// Get treatments
$treatmentQuery = "SELECT rt.*, u.full_name as assigned_to_name
                   FROM risk_treatments rt
                   LEFT JOIN users u ON rt.assigned_to = u.id
                   WHERE rt.risk_id = :risk_id
                   ORDER BY rt.created_at DESC";

$treatmentStmt = $db->prepare($treatmentQuery);
$treatmentStmt->bindParam(':risk_id', $risk_id);
$treatmentStmt->execute();
$treatments = $treatmentStmt->fetchAll(PDO::FETCH_ASSOC);

// Set headers for PDF download
header('Content-Type: application/pdf');
header('Content-Disposition: attachment; filename="Risk_Report_' . $risk_id . '_' . date('Y-m-d') . '.pdf"');

// Simple PDF generation (you can use libraries like TCPDF or FPDF for better formatting)
$html = "
<html>
<head>
    <title>Risk Report - {$risk['risk_name']}</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        .header { background: #E60012; color: white; padding: 20px; text-align: center; }
        .section { margin: 20px 0; padding: 15px; border: 1px solid #ddd; }
        .treatment { background: #f8f9fa; margin: 10px 0; padding: 10px; border-left: 4px solid #007bff; }
    </style>
</head>
<body>
    <div class='header'>
        <h1>Airtel Risk Management System</h1>
        <h2>Risk Report</h2>
    </div>
    
    <div class='section'>
        <h3>Risk Identification</h3>
        <p><strong>Risk ID:</strong> {$risk['id']}</p>
        <p><strong>Risk Name:</strong> {$risk['risk_name']}</p>
        <p><strong>Description:</strong> {$risk['risk_description']}</p>
        <p><strong>Cause:</strong> {$risk['cause_of_risk']}</p>
        <p><strong>Department:</strong> {$risk['department']}</p>
        <p><strong>Reported By:</strong> {$risk['reporter_name']}</p>
        <p><strong>Risk Owner:</strong> {$risk['owner_name']}</p>
        <p><strong>Date Created:</strong> " . date('M d, Y', strtotime($risk['created_at'])) . "</p>
    </div>
    
    <div class='section'>
        <h3>Risk Assessment</h3>
        <p><strong>Inherent Likelihood:</strong> {$risk['inherent_likelihood']}</p>
        <p><strong>Inherent Consequence:</strong> {$risk['inherent_consequence']}</p>
        <p><strong>Inherent Rating:</strong> {$risk['inherent_rating']}</p>
        <p><strong>Residual Likelihood:</strong> {$risk['residual_likelihood']}</p>
        <p><strong>Residual Consequence:</strong> {$risk['residual_consequence']}</p>
        <p><strong>Residual Rating:</strong> {$risk['residual_rating']}</p>
        <p><strong>Risk Level:</strong> {$risk['risk_level']}</p>
    </div>
    
    <div class='section'>
        <h3>Risk Treatments</h3>";

foreach ($treatments as $treatment) {
    $html .= "
        <div class='treatment'>
            <h4>{$treatment['treatment_name']}</h4>
            <p><strong>Description:</strong> {$treatment['description']}</p>
            <p><strong>Status:</strong> " . ucfirst(str_replace('_', ' ', $treatment['status'])) . "</p>
            <p><strong>Assigned To:</strong> {$treatment['assigned_to_name']}</p>
            <p><strong>Due Date:</strong> " . ($treatment['due_date'] ? date('M d, Y', strtotime($treatment['due_date'])) : 'Not set') . "</p>";
    
    if ($treatment['progress_update']) {
        $html .= "<p><strong>Progress:</strong> {$treatment['progress_update']}</p>";
    }
    
    $html .= "</div>";
}

$html .= "
    </div>
    
    <div class='section'>
        <p><strong>Report Generated:</strong> " . date('M d, Y H:i:s') . "</p>
        <p><strong>Generated By:</strong> {$_SESSION['email']}</p>
    </div>
</body>
</html>";

// For now, output HTML (you can integrate a proper PDF library later)
echo $html;
?>
